package edu.rutgers.axs.ctpf;

import java.io.*;
import java.lang.Math;
import java.nio.*;
import java.util.*;
import java.util.zip.GZIPInputStream;

import org.apache.lucene.document.*;
import org.apache.lucene.index.*;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.ScoreDoc;

import edu.rutgers.axs.sql.*;
import edu.rutgers.axs.indexer.*;

/** The fit data for CTPF. */
public class CTPFFit  {

    //public float[][] theta, epsilon; 
    public Vector<float[]> epsilon_plus_theta = new Vector<float[]>(), 
	epsilonlog= new Vector<float[]>(), thetalog= new Vector<float[]>(); 
    //public float[][] epsilon_shape, epsilon_rate;
    //public float[][] theta_shape, theta_rate; 
    //    private HashMap<Integer, String> internalID_to_aID = new HashMap<Integer, String>();
 
    /** Maps AID to CTPF internal ID and vice versa */
    public CTPFMap map;

    public boolean loaded;

    public boolean error = false;
    public String errmsg = null;
    void setError(String msg) {
	error = true;
	errmsg = msg;
    }

    private float avgScores[];
    
    public float getAvgScore(int i) {
	return i<avgScores.length? avgScores[i] : 0;
    }


    /** Input file format (TAB-separated):
	<pre>
0	0.000139
1	0.001495
2	0.000314
...
</pre>

The file was generated by Laurent. (Email 2014-04-14, "possible paper suggestion")
<pre>
As promised here are the mean scores for each paper:
/home/lc629/arxiv/fits/nusers120298-ndocs825708-nvocab14000-k250-batch-bin-vb-fa-ldainit/mean_paper_scores.tsv
</pre>

<p>The lines in this file are typically ordered same way as in
theta*.tsv etc files:
<pre>
[vm293@en-myarxiv02 ldainit.1]$ zcat theta_scale.tsv.gz|wc
 825708 208078416 2282034692
[vm293@en-myarxiv02 ldainit.1]$ wc mean_paper_scores.tsv 
  825708  1651416 13100218 mean_paper_scores.tsv
</pre>


FIXME: the current organization of this method (array avgScores[]
allocated inside it) does not support reading data from multiple files.

    */
    void loadAvgScores(File file, CTPFMap.Descriptor desc) throws IOException { 
	Logging.info("CTPFFit: loading avg scores from " + file);
	InputStream fis = new FileInputStream(file);
	if (file.getName().endsWith(".gz")) fis = new GZIPInputStream(fis);
	BufferedReader br = new BufferedReader(new InputStreamReader(fis));

	avgScores = new float[  desc.r1 + desc.offset];

        String line; 
	int lineCnt=0;
	int ignoreCnt = 0;
        while ((line = br.readLine()) != null) {
	    if (error) return;
	    lineCnt++;
            String[] parts = line.split("\t");
	    int riid = Integer.parseInt(parts[0]);
	    int iid = riid + desc.offset;
	    float score = (float)Double.parseDouble(parts[1]);
	    if (riid == 0) {
		Logging.warning("CPPFFit.loadAvgScores("+file+"): entering useless map entry for iid=" + iid + ", score=" + score);
	    } 
	    if (iid >= avgScores.length) {
		//		Logging.warning("CPPFFit.loadAvgScores("+file+"): ignoring useless map entry for iid=" + iid + ", score=" + score);
		ignoreCnt++;
		continue;
	    } 

 	    avgScores[iid] = score;
        }

        Logging.info("CTPFFit: read " + lineCnt + " lines from " + file);
	if (ignoreCnt>0) {
	    Logging.warning("CTPFFit: ignored " + ignoreCnt + "map entries with iid out of expected range");
	}
    }

} 
